### ISSUE TITLE
Checklist before first deploy

### ISSUE THREAD

**Issue by rithviknishad** [rithviknishad/rithviknishad#1]
## Components to create

- [x] Nav Bar Buttons
- [x] Social Link Buttons
- [x] Primary, Secondary Buttons
- [x] Project Cards

## APIs

- [x] Projects
- [x] Social Links

## Sections

- [x] NavBar
- [x] Home/Splash
- [x] Home/Intro
- [x] Home/Projects
- [x] Home/About (include skills)
- [x] Home/Social
- [x] Projects
- [x] About

## Other things:
- [x] Compress images before deploy
